require("plugin_config.colorscheme")
require("plugin_config.lualine")
require("plugin_config.telescope")
require("plugin_config.treesitter")
require("plugin_config.completions")
require("plugin_config.copilot")
require("plugin_config.lsp_config")
require("plugin_config.tabindentation")
require("plugin_config.other")
require("plugin_config.bookmarks")

