require("core.plugin_config.mason")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
-- require("core.plugin_config.spider")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.copilot")
require("core.plugin_config.trouble")
require("core.plugin_config.tabindentation")
require("core.plugin_config.other")

